# Generated by Django 2.2.7 on 2019-12-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='taks_desc',
            new_name='task_desc',
        ),
    ]
